### ISSUE TITLE
Decode an unverifiable JWT?

### ISSUE THREAD

**Issue by daleif** [jberger/Mojo-JWT#12]
If using Azure AD (OpenID Connect), the oauth2 response has two JWT tokens `id_token` and `access_token`. The former can be verified using normal means whereas the `access_token` cannot have its signature verified. This has been noted several times online, fx https://stackoverflow.com/questions/65149128/azure-access-token-invalid-signature-in-jwt-io  or https://stackoverflow.com/a/45318464/1195114, as soon as the header include a `nonce` the signature validation fails.

Is there any tools in Mojo::JWT to extract the claims without verifying the signature? Or do we have to to it by hand?  `$jwt->decode($token)` will croak when the signature validation fails.

**Comment by daleif** [comment]
Ahh, well, one can just get it via `$peek` and run `->decode` in an eval block

**Comment by jberger** [comment]
Yes, it is intentional that you cannot (easily) decode a jwt where the signature check fails. Reading some of those links it seems that you shouldn't have to either, however, if you choose to, yes the way you've found is how you can do it.

**Comment by daleif** [comment]
Noted.

Then it is just too bad that apparently one cannot use `$peek` when using `Mojo::JWT` via `Mojolicious::Plugin::OAuth2`. I think it is a coding error there (I've added an issue). Perhaps I should just decode the token manually.

**Comment by jberger** [comment]
Again, looking at those links you posted, it seem that most commenters agree that the tokens in question are not intended to be validated in that way.

**Comment by jberger** [comment]
It looks like you probably need to change the scopes parameter in your request

**Comment by daleif** [comment]
> 

I saw that comment as well, here I'm just using the defaults. For now I'll just manually extract the payload from the JWT.

**Comment by jberger** [comment]
I suppose you could also use the peek callback to set the algorithm to `none` which would disable verification as though the token were not signed. You'd also have to set `allow_none` too

**Comment by daleif** [comment]
Note that for `Mojo::JWT` using the `peek` callback +eval works just fine. But I'm using `Mojolicious::Plugin::OAuth2` which provides a wrapper for the `$jwt->decode` call, and as far as I can see they've made that wrapper such that one cannot pass on the callback. I've raised an issue on their repro.
