### ISSUE TITLE
Usage of JWK for public key?

### ISSUE THREAD

**Issue by pierre-vigier** [jberger/Mojo-JWT#6]
When creating a JWT from this module, it's working perfectly, but some OAuth or OpenID server returning JWT use a JSON Web Key to verify the signature of a token.
Maybe it could be a good idea to consider accepting also a hash in the public attribute, that could be a JWK structure. A JWK is a JSON representation of a cryptographic key, so instead of giving a pem or x509 string, it has a modulus, exponent and a few other component.

module 'Crypt::JWT' for instance propose that

**Comment by jberger** [comment]
I would consider a PR for it but I don't have the time to do it now, myself. The API might be a little tricky.

**Comment by pierre-vigier** [comment]
Indeed, API could be tricky, in the case of google openid for instance, they give that url:
https://www.googleapis.com/oauth2/v3/certs
from there there are severals keys in JWK format
To verify the token, one first need to get the kid from the JWT header and build the correct key.
Giving the url providing the keys could be a way but those keys should be kept in cache, and not re-downloaded every time, following the cache headers

It seems those "details", how to cache and how long should be outside of the scope of the module indeed.

Any ideas of API ? something like public_from_JWK methods, that would take an arrays of JWK format? or adding an extra method
my $bool = $jwt->verify_rsa_jwk($size, $payload, $signature, [$jwk_keys]);
that would take the kid from the header and search for corresponding keys in the array, then call public() to set the key and verify using $jwt->verify_rsa
